### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by 20jasper** [20jasper/interview_question_api_graphql#5]
Only make PRs for minor versions and patches rust

Make prs for github actions updates as well
```yaml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
